export const MAX_LOG_BYTES = 1_000_000; // ~1 MB
export const MAX_LOG_CHARS = 1_000_000;
export const MAX_ANALYZE_PER_MINUTE = 10;
export const MAX_UPLOAD_PER_MINUTE = 20;
export const UPLOAD_STALE_HOURS = 24;
export const MAX_SEARCH_PER_MINUTE = 30;
export const MAX_EVALUATE_PER_MINUTE = 20;
export const MAX_SUMMARY_LENGTH = 8_000;
export const MAX_ATTACK_TYPE_LENGTH = 200;
export const MAX_TIMELINE_EVENTS = 100;
export const MAX_RECOMMENDATIONS = 30;
export const MAX_RECOMMENDATION_LENGTH = 500;
export const MAX_TIMELINE_EVENT_LENGTH = 500;
export const RAW_RESPONSE_MAX_CHARS = 4_000;
export const RAG_TOP_K = 5;
export const EMBEDDING_DIMENSIONS = 768;
export const EMBEDDING_BATCH_SIZE = 16;
export const RRF_RANK_CONSTANT = 60;
