import type { ResearchSnapshot } from "@/lib/research-snapshot";

export function buildFullResearchReport(snapshot: ResearchSnapshot): string {
  const { overview, experiments, questions, leaderboard, scenarios } = snapshot;
  const date = new Date().toISOString().split("T")[0];

  const lines: string[] = [
    "# Argus — Research Evaluation Report",
    "",
    `**Generated:** ${date}`,
    "",
    "---",
    "",
    "## Executive Summary",
    "",
    "Argus is an open research platform for evaluating LLM-assisted Security",
    "Operations Center (SOC) log triage. The current phase uses **Google Gemini** as",
    "an analysis baseline while building the labeled corpus, metrics framework, and",
    "controlled experiments required to **fine-tune an open-source security model**",
    "on authentication and incident logs with cybersecurity-grounded supervision.",
    "",
    "### Current phase",
    "- **Baseline model:** Gemini (structured JSON incident analysis)",
    "- **Target:** Fine-tuned open-source model trained on labeled SOC scenarios",
    "- **Corpus:** 10 synthetic attack scenarios with ground-truth labels",
    "- **Retrieval:** Hybrid FTS + semantic embeddings (MITRE + playbooks)",
    "",
    "### Key metrics (this report)",
    `- Scenarios in corpus: **${overview.totalScenarios}**`,
    `- Active experiments: **${overview.activeExperiments}**`,
    `- Evaluation runs: **${overview.totalRuns}**`,
    overview.bestAccuracy !== null
      ? `- Best accuracy: **${(overview.bestAccuracy * 100).toFixed(1)}%**`
      : "- Best accuracy: *pending runs*",
    overview.avgHallucination !== null
      ? `- Mean hallucination rate: **${(overview.avgHallucination * 100).toFixed(1)}%**`
      : "",
    "",
    "---",
    "",
    "## Research Vision",
    "",
    "Commercial APIs (Gemini) enable rapid prototyping. The research trajectory is:",
    "",
    "1. **Build** labeled log fixtures + ground-truth schema",
    "2. **Evaluate** retrieval, input format, and prompt strategies",
    "3. **Fine-tune** an open-source model on SOC log → structured incident JSON",
    "4. **Compare** fine-tuned model vs Gemini baseline on the same metrics",
    "",
    "This report documents step 2. Results inform training data design and",
    "evaluation criteria for step 3.",
    "",
    "---",
    "",
    "## Evaluation Corpus",
    "",
    "| Scenario | Difficulty | MITRE | Runs | Best accuracy |",
    "|----------|------------|-------|------|---------------|",
    ...scenarios.map(
      (s) =>
        `| ${s.name} | ${s.difficulty} | ${s.mitre.join(", ")} | ${s.runCount} | ${s.bestAccuracy !== null ? `${(s.bestAccuracy * 100).toFixed(1)}%` : "—"} |`,
    ),
    "",
    "---",
    "",
    "## Active Experiments",
    "",
    ...experiments.flatMap((exp) => [
      `### ${exp.name} (\`${exp.id}\`)`,
      "",
      exp.description,
      "",
      `- Runs: ${exp.runs}`,
      `- Best accuracy: ${exp.bestAccuracy !== null ? `${(exp.bestAccuracy * 100).toFixed(1)}%` : "—"}`,
      `- Variants: ${exp.variants.map((v) => v.label).join(", ")}`,
      "",
    ]),
    "---",
    "",
    "## Research Questions & Findings",
    "",
    ...questions.flatMap((q) => [
      `### ${q.id}`,
      "",
      `**Question:** ${q.question}`,
      "",
      `**Status:** ${q.status.replace("_", " ")}`,
      "",
      `**Finding:** ${q.finding ?? "Pending evaluation."}`,
      "",
      `*Evidence runs: ${q.evidenceRuns}*`,
      "",
    ]),
    "---",
    "",
    "## Results Leaderboard (top 15)",
    "",
    "| Rank | Experiment | Scenario | Variant | Accuracy | Hallucination | Latency |",
    "|------|------------|----------|---------|----------|---------------|---------|",
    ...leaderboard.slice(0, 15).map((row, i) =>
      `| ${i + 1} | ${row.experiment} | ${row.scenario} | ${row.variant} | ${(row.accuracy * 100).toFixed(1)}% | ${(row.hallucinationRate * 100).toFixed(1)}% | ${Math.round(row.latencyMs)}ms |`,
    ),
    "",
    "---",
    "",
    "## Methodology",
    "",
    "- **Ground truth:** attack type, severity, MITRE IDs, keywords, entities, playbook themes",
    "- **Metrics:** accuracy, attack_type_accuracy, severity_accuracy, mitre_mapping_accuracy,",
    "  investigation_quality, recommendation_quality, analyst_utility_score, hallucination_rate",
    "- **Runner:** `npm run experiment:all` (batch evaluation)",
    "- **Model:** Gemini via AnalysisOrchestrator (temperature 0.2)",
    "",
    "---",
    "",
    "## Next Steps",
    "",
    "1. Complete full corpus evaluation (`npm run experiment:all`)",
    "2. Export training pairs from fixtures + ground truth",
    "3. Fine-tune open-source model (e.g. Llama/Mistral) on SOC structured output",
    "4. Re-run identical experiments on fine-tuned endpoint",
    "5. Publish comparison: Gemini baseline vs fine-tuned open-source model",
    "",
    "---",
    "",
    "*Argus Research Lab — open cybersecurity AI evaluation*",
  ];

  return lines.filter((l) => l !== undefined).join("\n");
}
