import { InvestigationMetricCard } from "@/features/investigation/components/investigation-metric-card";
import { InvestigationSection } from "@/features/investigation/components/investigation-section";
import type { CommandCenterMetrics } from "@/types/investigation";
import { formatDate } from "@/utils/format";

type CommandCenterProps = {
  metrics: CommandCenterMetrics;
  generatedAt: string;
};

export function CommandCenter({ metrics, generatedAt }: CommandCenterProps) {
  return (
    <InvestigationSection
      id="summary"
      title="Incident Command Center"
      description="Executive summary of detected activity, severity distribution, and analysis confidence."
    >
      <div className="mb-6 rounded-lg border border-border bg-card p-6">
        <p className="text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
          Argus Investigation Report
        </p>
        <p className="mt-2 text-sm text-muted-foreground">
          Generated by{" "}
          <span className="font-medium text-foreground">Argus AI Analyst</span>
          {" · "}
          {formatDate(generatedAt)}
        </p>
      </div>

      <div className="grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-3 lg:grid-cols-4">
        <InvestigationMetricCard
          label="Total Incidents"
          value={metrics.totalIncidents}
        />
        <InvestigationMetricCard
          label="Critical"
          value={metrics.critical}
          variant="critical"
        />
        <InvestigationMetricCard
          label="High"
          value={metrics.high}
          variant="high"
        />
        <InvestigationMetricCard
          label="Medium"
          value={metrics.medium}
          variant="warning"
        />
        <InvestigationMetricCard
          label="Confidence"
          value={`${metrics.confidence}%`}
          variant="success"
        />
        <InvestigationMetricCard
          label="Logs Processed"
          value={metrics.logsProcessed}
        />
        <InvestigationMetricCard
          label="Processing Time"
          value={`${(metrics.processingTimeMs / 1000).toFixed(1)}s`}
        />
      </div>
    </InvestigationSection>
  );
}
