"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_content from './dashboard-content.bones.json'
import _incidents_list from './incidents-list.bones.json'
import _log_search from './log-search.bones.json'
import _log_search_results from './log-search-results.bones.json'

configureBoneyard({"color":"oklch(0.97 0 0)","darkColor":"oklch(0.269 0 0)","animate":"shimmer","shimmerColor":"oklch(0.99 0 0)","darkShimmerColor":"oklch(0.32 0 0)","speed":"1.8s","transition":300})

registerBones({
  "dashboard-content": _dashboard_content,
  "incidents-list": _incidents_list,
  "log-search": _log_search,
  "log-search-results": _log_search_results,
})
